routes/web.php
<?php

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('employee', 'EmployeeController');
Route::get('api/employee', 'EmployeeController@getData');

Route::resource('propagation', 'PropagationController');
Route::get('api/propagation', 'PropagationController@getData');
Route::get('/propagation/{id}/delete', 'PropagationController@delete')->name('propagation.delete');

Route::resource('course', 'CourseController');
Route::get('api/course', 'CourseController@getData');

Route::resource('proponent', 'ProponentController');
Route::get('api/proponent/{type}', 'ProponentController@getData');
Route::get('/proponent/solicitacoes/aprovar', 'ProponentController@showProponentAprovado')->name('proponent.ap');
Route::get('/proponent/{id}/aprovar', 'ProponentController@toApprove')->name('proponent.aprovar');
Route::get('/proponent/{id}/recusar', 'ProponentController@refuse')->name('proponent.recusar');

Route::resource('turma', 'TurmaController', ['except' => ['create']]);
Route::get('/turma/create/{id}', 'TurmaController@create')->name('turma.create');
Route::get('/turma/{idTurma}/{idCurso}/editData', 'TurmaController@editData')->name('turma.editData');
Route::get('api/requested/turmas', 'TurmaController@getData');
Route::get('api/requested/turmas/toAprove', 'TurmaController@toAprove');
Route::get('/turma/{id}/aproveEdition', 'TurmaController@aproveEdition');
Route::get('turma/requested/approved', 'TurmaController@approved')->name('turma.approved');
Route::get('api/turma/requested/approved', 'TurmaController@showApproved')->name('turma.showApproved');
Route::get('turma/requested/canceled', 'TurmaController@canceled')->name('turma.canceled');
Route::get('api/turma/requested/canceled', 'TurmaController@showCanceled')->name('turma.showCanceled');
Route::get('turmas/index/Abertas', 'TurmaController@indexAbertas')->name('turmas.indexAbertas');
Route::get('api/turma/index/abertas', 'TurmaController@showAbertas')->name('turma.showAbertas');

Route::resource('notice', 'NoticeController');
Route::get('/notice/{id}/solicitarNumero', 'NoticeController@solicitarNumero')->name('notice.solicitarNumero');
Route::get('/notice/{id}/delete', 'NoticeController@delete')->name('notice.delete');
Route::get('api/notice', 'NoticeController@getData');
Route::get('/notice/{id}/{token}/cadastrarNumero','NoticeController@cadastrarNumero')->name('notice.cadastrarNumero');
Route::post('/notice/storeNumber/{id}', 'NoticeController@storeNumber')->name('notice.storeNumber');
Route::get('/notice/{id}/download', 'NoticeController@pdf')->name('notice.download');
Route::get('/notice/{id}/edital', 'NoticeController@edital')->name('notice.edital');
Route::get('notice/{id}/publicar', 'NoticeController@publicar')->name('notice.publicar');
Route::get('notice/index/Publicados', 'NoticeController@indexPublicado')->name('notice.indexPublicado');









Route::resource('student', 'StudentController');

resources/views/employee.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			@can('has-permission', 'employee')
			<div class="tituloPag"><p>Editar Dados do Servidor</p></div>
			<div class="panel-body putmargin">
					<form class="form-horizontal my-from" method="POST" action="{{ route('employee.update', $user->id) }}">
							{{ csrf_field() }}
							{{ method_field('PUT') }}
							<input type="hidden" name="id" value="{{ $user->id }}" />
							<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
								<label for="name" class="my-form-label">Nome</label>
								<div class="input-field">
									<input id="name" type="text" class="form-control" name="name" value="{{ $user->name ?  $user->name : old('name') }}" required autofocus>

									@if ($errors->has('name'))
									<span>
										<strong class="help-block">{{ $errors->first('name') }}</strong>
									</span>
									@endif
								</div>
							</div>
							<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
								<label for="email" class="my-form-label">E-Mail</label>
								<div class="input-field">
									<input id="email" type="email" class="form-control" name="email" value="{{ $user->email ?  $user->email : old('email') }}" required>

									@if ($errors->has('email'))
									<span>
										<strong class="help-block">{{ $errors->first('email') }}</strong>
									</span>
									@endif
								</div>
							</div>
							<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
								<label for="password" class="my-form-label">Nova Senha</label>
								<div class="input-field">
									<input id="password" type="password" class="form-control" name="password">

									@if ($errors->has('password'))
									<span>
										<strong class="help-block">{{ $errors->first('password') }}</strong>
									</span>
									@endif
								</div>
							</div>
							<div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
								<label for="password_confirmation" class="my-form-label">Confirme Senha</label>
								<div class="input-field">
									<input id="password_confirmation" type="password" class="form-control" name="password_confirmation">

									@if ($errors->has('password_confirmation'))
									<span>
										<strong class="help-block">{{ $errors->first('password_confirmation') }}</strong>
									</span>
									@endif
								</div>
							</div>
							<div class="form-group{{ $errors->has('coordinator') ? ' has-error' : '' }} col-md-3">
								<input class="custom-control-input" type="checkbox" id="coordinator" name="coordinator"  @if ( old('coordinator')) checked @endif value="1"  />
								<label for="coordinator" class="my-form-label">Coordenador</label>
								@if ($errors->has('coordinator'))
								<span class="help-block">
									<strong>{{ $errors->first('coordinator') }}</strong>
								</span>
								@endif
							</div>
							<div class="col-md-6">
								<input class="custom-control-input" type="checkbox" id="active" name="active"  @if ( old('active')) checked @endif value="1"  />
								<label for="active" class="my-form-label">Ativo</label>
								@if ($errors->has('active'))
								<span class="help-block">
									<strong>{{ $errors->first('active') }}</strong>
								</span>
								@endif
							</div>
						<br>
						<div class="form-group col-md-12">
							<button type="submit" class="btn bnt-padrao col-md-3">
								ENVIAR
							</button>
						</div>
					</form>
				</form>
			</div>
			@endcan
		</div>
	</div>
</div>
@endsection

resources/views/mail.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<title>IFSP - Extensão</title>
</head>
<body>
	<div class="container">
		<center>
			<div style="height:20px;">
				<h1>Sistema CEX</h1>
			</div>
		</center>
		<h2> Olá!!</h2><br/>
		@if($proponent->status == 'Solicitado')
		<p>
			Sua solicitação para obter acesso foi enviada para avovação. Aguarde resposta.
		</p>
		@else
		<p> Sua Solicitação foi Apovada!
			Você pode acessar o Sistema CEX utilizando o email {{$proponent->user->email}} e a senha informada no momento do cadastro.<br />
			Caso não tenha acesso ao dados do cadastro solicite alteração de senha  disponivel na tela de login.
		</p>
		@endif
		<br>
		<p>	Com os melhores cumprimentos <br>
			CEX- Guarulhos
		</p>
		<center>
			<div style="height:20px;">
				<p>@CEX Todos os direitos reservados</p>
			</div>
		</center>

	</div>

</body>
</html>

resources/views/mailEditAprov.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<title>IFSP - Extensão</title>
</head>
<body>
	<div class="container">
		<center>
			<div style="height:20px;">
				<h1>Sistema CEX</h1>
			</div>
		</center>
		<h2> Olá!!</h2><br/>
		@if($turma->status == 'cancelada')
		<p>
			Sua solicitação para abertura de da turma {{$turma->name}} realizada no dia {{strftime('%d de %B de %Y', strtotime($turma->date))}}
		</p>
		@else
		<p> Sua solição para a abertura da {{$turma->name}} realizada no dia {{strftime('%d DE %B DE %Y', strtotime($turma->date))}} foi alterada. É necessaria a aprovação das alterações para dar andamento no processo. <a href="{{$link}}">Veja as alterações</a><br>
		</p>
		@endif
		<br>
		<p>	Com os melhores cumprimentos <br>
			CEX- Guarulhos
		</p>
		<center>
			<div style="height:20px;">
				<p>@CEX Todos os direitos reservados</p>
			</div>
		</center>

	</div>

</body>
</html>

resources/views/mailSendSolicitacao.blade.php
<div class="container">

Informe o numero de edital

<a href="{{$link}}">{{$link}}</a><br>
</div>

resources/views/mailSendSolicitacaoPublicacao.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<title>IFSP - Extensão</title>
</head>
<body>
	<div class="container">
		<center>
			<div style="height:20px;">
				<h1>Sistema CEX</h1>
			</div>
		</center>
		<h2> Olá!!</h2><br/>
		<p>
			Abriremos uma novas turmas!
			<br />
			Enviamos o Edital Numero {{$notice->number}} em anexo
			<br> Pedimos que acesse os links abaixo realize o upload do banner!
			<br>
			<button type="button" name="button">
				<a href="{{$linkImage}}">Banner</a>
			</button> <br>
			<br>
		</p>
		<br>
		<p>	Com os melhores cumprimentos <br>
			CEX- Guarulhos
		</p>
		<center>
			<div style="height:20px;">
				<p>@CEX Todos os direitos reservados</p>
			</div>
		</center>
	</div>
</body>
</html>

resources/views/mailrequestProntuario.blade.php
<div class="container">

Informe o numero de edital

<a href="{{$link}}">{{$link}}</a><br>
</div>

resources/views/notice.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="tituloPag"><p>Editais</p></div>
			<div class="panel-body putmargin">
				@if (isset($notice->id))
				<form class="form-horizontal my-from" method="POST" action="{{ route('notice.update', $notice->id) }}">
					{{ csrf_field() }}
					{{ method_field('PUT') }}
					@else
					<form class="form-horizontal my-from" method="POST" action="{{ route('notice.store') }}">
						{{ csrf_field() }}
						@endif
						<div class="col s12">
							<select name="t[]" multiple>
								<option value="" disabled>Selecione as Turmas</option>
								@foreach ($allTurmas as $turma  => $value)
								<option value="{{$turma}}"
								@foreach ($notice->turmas as $t)
								{{ $t->id == $turma || old('t') == $value  ?  'selected' : '' }}
								@endforeach
								>{{$value}}</option>
								@endforeach
							</select>
							<label>Turmas</label>
							@if ($errors->has('t'))
							<span>
								<strong class="red-text">{{ $errors->first('t') }}</strong>
							</span>
							@endif
						</div>
						<div class="col s6">
							<label for="number">Numero do edital</label>
							<input type="text"  value="{{ $notice->number ?  $notice->number : old('number') }} " name="number">
							@if ($errors->has('number'))
							<span>
								<strong class="red-text">{{ $errors->first('number') }}</strong>
							</span>
							@endif
						</div>
						<div class="col s12">
							<label for="postResult">Data da publicação do resultado *</label>
							<input type="text"  value="{{ $notice->postResult ?  $notice->postResult : old('postResult') }} " name="postResult" class="datepicker">
							@if ($errors->has('postResult'))
							<span>
								<strong class="red-text">{{ $errors->first('postResult') }}</strong>
							</span>
							@endif
						</div>
						<div class="col s6">
							<label for="registrationstartdate">Data de inicio da Matricula</label>
							<input type="text"  value="{{ $notice->registrationstartdate ?  $notice->registrationstartdate : old('registrationstartdate') }} " name="registrationstartdate" class="datepicker">
							@if ($errors->has('registrationstartdate'))
							<span>
								<strong class="red-text">{{ $errors->first('registrationstartdate') }}</strong>
							</span>
							@endif
						</div>
						<div class="col s6">
							<label for="registrationclosingdate">Data de termino das Matricula</label>
							<input type="text"  value="{{ $notice->registrationclosingdate ?  $notice->registrationclosingdate : old('registrationclosingdate') }} " name="registrationclosingdate" class="datepicker">
							@if ($errors->has('registrationclosingdate'))
							<span>
								<strong class="red-text">{{ $errors->first('registrationclosingdate') }}</strong>
							</span>
							@endif
						</div>
						<div class="col s6">
							<label for="startdate" >Data de inicio das inscrições</label>
							<input type="text" value="{{ $notice->startdate ?  $notice->startdate : old('startdate') }} " name="startdate" class="datepicker">
							@if ($errors->has('startdate'))
							<span>
								<strong class="red-text">{{ $errors->first('startdate') }}</strong>
							</span>
							@endif
						</div>
						<div class="col s6">
							<label for="closingdate">Data de termino das inscrições</label>
							<input type="text"  value="{{ $notice->closingdate ?  $notice->closingdate : old('closingdate') }} " name="closingdate" class="datepicker">
							@if ($errors->has('closingdate'))
							<span>
								<strong class="red-text">{{ $errors->first('closingdate') }}</strong>
							</span>
							@endif
						</div>
						<div class="col s12">
							<label for="testDay">Data da Prova</label>
							<input type="text"  value="{{ $notice->testDay ?  $notice->testDay : old('testDay') }} " name="testDay" class="datepicker">
							@if ($errors->has('testDay'))
							<span>
								<strong class="red-text">{{ $errors->first('testDay') }}</strong>
							</span>
							@endif
						</div>




						<div class="form-group">
							<button type="submit" class="btn bnt-padrao col-md-3">
								ENVIAR
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	@endsection

resources/views/proponent.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="tituloPag"><p>Dados do Proponente</p></div>
			<div class="panel-body putmargin">
				@if (isset($user->id))
				<form class="form-horizontal my-from" method="POST" action="{{ route('proponent.update', $user->id) }}">
					{{ csrf_field() }}
					{{ method_field('PUT') }}
					@else
					<form class="form-horizontal my-from" method="POST" action="{{ route('proponent.store') }}">
						{{ csrf_field() }}
						@endif
						<input type="hidden" name="id" value="{{ $user->id ?  $user->id : '' }}" />
						<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
								<div class="input-field">
								<input placeholder="Nome:" id="name" type="text" class="form-control" name="name" value="{{ $user->name ?  $user->name : old('name') }}" required autofocus>

								@if ($errors->has('name'))
								<span>
									<strong class="help-block">{{ $errors->first('name') }}</strong>
								</span>
								@endif
							</div>
						</div>

						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<div class="input-field">
								<input placeholder="E-Mail:" id="email" type="email" class="form-control" name="email" value="{{ $user->email ?  $user->email : old('email') }}" required>

								@if ($errors->has('email'))
								<span>
									<strong class="help-block">{{ $errors->first('email') }}</strong>
								</span>
								@endif
							</div>
						</div>

						@if (!isset($user->id))
						<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
							<div class="input-field">
								<input placeholder="Senha:" id="password" type="password" class="form-control" name="password" required>

								@if ($errors->has('password'))
								<span>
									<strong class="help-block">{{ $errors->first('password') }}</strong>
								</span>
								@endif
							</div>
						</div>

						<div class="form-group">
							<div class="input-field">
								<input placeholder="Confirmar senha:"id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
							</div>
						</div>
						@endif


						<div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
							<div>
								<select name="typeProp" class="form-control">
									<option value="" disabled selected>Selecione o proponente</option>
									<option value="Aluno" @if(isset($user->proponent) && $user->proponent->type == 'Aluno' || old('typeProp') == 'Aluno'  ) selected @endif >Aluno</option>
									<option value="Servidor" @if(isset($user->proponent) && $user->proponent->type == 'Servidor' || old('typeProp') == 'Servidor') selected @endif>Servidor</option>
									<option value="Professor" @if(isset($user->proponent) && $user->proponent->type == 'Professor' || old('typeProp') == 'Professor') selected @endif>Professor</option>
								</select>
							</div>
						</div>
						@if (isset($user->id))
						<div class="form-group">
							<input type="checkbox" class="custom-control-input" id="active" name="active"   @if ($user->active == true) checked @endif value="1" />
							<label for="active" class="my-form-label">Ativo</label>
							@if ($errors->has('active'))
							<span>
								<strong class="help-block">{{ $errors->first('active') }}</strong>
							</span>
							@endif
						</div>
						@endif
						<br />
						<div class="form-group">
							<button type="submit" class="btn bnt-padrao col-md-3">
								ENVIAR
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/showApprovedTurmas.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="tituloPag"><p>Solicitações de turmas aprovadas</p></div>
			<div class="panel-body putmargin">
					<vc-paginate  source="/tcc/public/api/turma/requested/approved"  Componente="RequestedTurma" auth="avaliada"></vc-paginate>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/showCourses.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="tituloPag"><p>Cursos</p></div>
			<div class="panel-body putmargin">
				<vc-paginate  source="/tcc/public/api/course" Componente="Course" auth="{{$auth}}"></vc-paginate>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/showNoticePublicado.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			@can('has-permission', 'employee')
			<div class="tituloPag"><p>Editais Publicados</p></div>
			<div class="panel-body putmargin">
				<vc-paginate  source="/tcc/public/api/notice" type="publicado" title="Editais" Componente="Notice"></vc-paginate>
			</div>
			@endcan
		</div>
	</div>
</div>
@endsection

resources/views/showPropagation.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="tituloPag"><p>Divulgação de cursos</p></div>
			<div class="panel-body putmargin">
				<vc-paginate  source="/tcc/public/api/propagation" Componente="Propagation"></vc-paginate>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/showProponents.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="tituloPag"><p>Proponentes</p></div>
			<div class="panel-body putmargin">
				<vc-paginate  source="/tcc/public/api/proponent/false" Componente="Proponente"></vc-paginate>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/showProponentsApove.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="tituloPag"><p>Proponentes</p></div>
			<div class="panel-body putmargin">
				<vc-paginate  source="/tcc/public/api/proponent/solicitados" Componente="Proponente"></vc-paginate>
			</div>
		</div>
	</div>
</div>
@endsection